name: Update PSChristmasTree Module Version And Changelog

on:
  workflow_run:
    workflows: ["Release PSChristmasTree Module on Github"]
    types:
      - completed

jobs:
  NewVersionAndChanlog:
    name: Update Module Version
    runs-on: ubuntu-latest
    env: 
      CI_COMMIT_VERSION_MESSAGE: ":bookmark: Update module version"
      CI_COMMIT_CHANGELOG_MESSAGE: ":loud_sound: Update CHANGELOG.md"
      CI_COMMIT_AUTHOR: Continuous Integration
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup PowerShell module cache
        id: cacher
        uses: actions/cache@v3
        with:
          path: "~/.local/share/powershell/Modules"
          key: ${{ runner.os }}-PSInvokeBuild
          restore-keys: ${{ runner.os }}-PSInvokeBuild
      - name: Install InvokeBuild from PSGallery
        if: steps.cacher.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module InvokeBuild -Force   
      - name: Build artifacts
        shell: pwsh
        run: |
          Invoke-Build . -Configuration "Release" -Verbose
      - name: Use gem
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
      - name: Install github-changelog-generator
        run: gem install github_changelog_generator
      - name: Generate CHANGELOG
        run: github_changelog_generator -u Sofiane-77 -p PSChristmasTree --token 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
      - name: Commit Version Module
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "19627401+Sofiane-77@users.noreply.github.com"
          git add PSChristmasTree/PSChristmasTree.psd1
          git commit -m "${{ env.CI_COMMIT_VERSION_MESSAGE }}"
          git push
      - name: Commit CHANGELOG
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "19627401+Sofiane-77@users.noreply.github.com"
          git add CHANGELOG.MD
          git commit -m "${{ env.CI_COMMIT_CHANGELOG_MESSAGE }}"
          git push