name: Publish PSChristmasTree Module on Powershell Gallery

on:
  workflow_run:
    workflows: ["Release PSChristmasTree Module on Github"]
    types:
      - completed

jobs:
  publish-to-gallery:
    name: Publish on Powershell Gallery
    runs-on: ubuntu-latest
    steps:
        - name: Check out repository code
          uses: actions/checkout@v3
        - name: Setup PowerShell module cache
          id: cacher
          uses: actions/cache@v3
          with:
            path: "~/.local/share/powershell/Modules"
            key: ${{ runner.os }}-PSInvokeBuild
            restore-keys: ${{ runner.os }}-PSInvokeBuild
        - name: Install InvokeBuild from PSGallery
          if: steps.cacher.outputs.cache-hit != 'true'
          shell: pwsh
          run: |
            Set-PSRepository PSGallery -InstallationPolicy Trusted
            Install-Module InvokeBuild -Force   
        - name: Build and publish
          env:
            NUGET_KEY: ${{ secrets.NuGetApiKey }}
          shell: pwsh
          run: |
            Invoke-Build . -Configuration "Release" -NuGetApiKey $env:NUGET_KEY -Verbose
          
