name: Publish PowerShell Module

on:
  release:
    types: [released]

jobs:
  publish-to-gallery:
    runs-on: ubuntu-latest
    steps:
        - name: Check out repository code
          uses: actions/checkout@v3
        - name: Setup PowerShell module cache
          id: cacher
          uses: actions/cache@v3
          with:
            path: "~/.local/share/powershell/Modules"
            key: Ubuntu-PSInvokeBuild
        - name: Install InvokeBuild from PSGallery
          if: steps.cacher.outputs.cache-hit != 'true'
          shell: pwsh
          run: |
            Set-PSRepository PSGallery -InstallationPolicy Trusted
            Install-Module InvokeBuild -Force   
        - name: Build and publish
          env:
            NUGET_KEY: ${{ secrets.NuGetApiKey }}
          shell: pwsh
          run: |
            Invoke-Build . build.ps1 -Configuration "Release" -NuGetApiKey $env:NUGET_KEY -Verbose
          
