name: Release PSChristmasTree Module on Github

on:
  push:
    tags:
      - 'v*.*.*.*'

jobs:
  build_release:
    name: Release on Github
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install InvokeBuild from PSGallery
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module InvokeBuild -Force   
      - name: Build artifacts
        shell: pwsh
        run: |
          Invoke-Build . -Configuration "Release" -Verbose
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          name: ${{  github.ref_name }}
          tag_name: ${{ github.ref }}
          fail_on_unmatched_files: true
          generate_release_notes: true
          files: |
            /home/runner/work/PSChristmasTree/PSChristmasTree/Build/Release/PSChristmasTree/*.zip
